app:
  bounded-context: restaurant
  domain: restaurant
  microservice: order
logging:
  level:
    com:
      training:
        spring:
          order:
            integration:
              restaurant: debug
feign:
  client:
    config:
      default:
        error-decoder: com.training.spring.client.error.MyErrorDecoder
        connect-timeout: 1000
        read-timeout: 5000
        logger-level: full
        metrics:
          enabled: true
      RESTAURANT:
        request-interceptors:
        - com.training.spring.order.integration.restaurant.MyRequestInterceptor
  httpclient:
    enabled: true
info:
  app:
    port: ${server.port}
    version: '@project.version@'
  osman:
    ali: ali
    deneme: osman
server:
  error:
    include-binding-errors: always
    include-exception: true
    include-message: always
  port: ${app.port:11000}
spring:
  application:
    name: order
  config:
    import: configserver:http://127.0.0.1:8888
  cloud:
    loadbalancer:
      retry:
        enabled: true
        max-retries-on-next-service-instance: 3
        max-retries-on-same-service-instance: 0
        retry-on-all-operations: true
      health-check:
        initial-delay: 10000
        interval: 2000
resilience4j:
  retry:
    instances:
      restaurantmenu:
        max-attempts: 2
        wait-duration: 100
        result-predicate: com.training.spring.resilience.MyResultPredicate
        retry-exception-predicate: com.training.spring.resilience.MyExceptionPredicate
  circuitbreaker:
    metrics:
      enabled: true
    instances:
      cbrestaurant:
        sliding-window-size: 20
        sliding-window-type: count-based
        minimum-number-of-calls: 10
        failure-rate-threshold: 30
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 5
        max-wait-duration-in-half-open-state: 5s
        automatic-transition-from-open-to-half-open-enabled: false
        allow-health-indicator-to-fail: true
        register-health-indicator: true
        slow-call-duration-threshold: 500
        slow-call-rate-threshold: 30