server:
  port: ${app.port:12000}
  tomcat:
    max-connections: 500
    threads:
      max: 200
      min-spare: 50
    max-keep-alive-requests: 200
    keep-alive-timeout: 120000
    max-swallow-size: 2000000
spring:
  application:
    name: notify
  config:
    import: configserver:http://127.0.0.1:8888

